### ISSUE TITLE
Error when opening an mp3: System.IO.FileFormatException: The image cannot be decoded.

### ISSUE THREAD

**Issue by MetaflameDragon** [Dreregon/Tag-Draco#1]
Exception thrown when attempting to open this mp3 file:
https://www.dropbox.com/s/6a2y0kojxkw3xnd/005%20-%20Ruins.mp3?dl=0

Doesn't occur with this file:
https://www.dropbox.com/s/pn15tz5zegajpyv/004%20-%20Fallen%20Down.mp3?dl=0

Head of exception (full txt attached):
[report210108_01.txt](https://github.com/Adrelyr/Tag-Draco/files/5786463/report210108_01.txt)
```
************** Exception Text **************
System.IO.FileFormatException: The image cannot be decoded. The image header might be corrupted. ---> System.Runtime.InteropServices.COMException: The image header is unrecognized. (Exception from HRESULT: 0x88982F61)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TagDraco.GUI.MainGUI.LoadMetaData(Int32 index)
   at TagDraco.GUI.MainGUI.openToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by draconicode** [comment]
Looked into it, and it looks like the file's embedded picture is indeed corrupted. I did fix the crashing part, the software will now continue loading the file, it will just not load the image.
Releasing a bugfix release right now!

The problematic thing was bitmapImage.EndInit(), it was crashing there.

Thanks for the feedback ^^ And let me know if everything is fixed once I release the update
